app.js
controllers/roomController.js
migrations/20230515074818-game_room.js
models/GameRoom.js
models/index.js
routes/roomRoute.js
services/roomService.js

api create room api

---

app.js
package-lock.json
package.json

feat: morgan 설정

---

app.js
controllers/socketController.js
package-lock.json
package.json

잘 되는지 위처럼 이런저런 테스트를 해보긴 했는데...

feat: 방 생성하기 소켓 구현

---

controllers/socketController.js
models/GameStatus.js
models/index.js
services/roomService.js

테스트....하기 위한.. json 데이터 셋....
```
{
"roomId": 142,
"userId": "babo",
"isMyTurn": false,
"orderNum": 1,
"sheepNum": 1,
"pigNum":1,
"cowNum":1,
"woodNum":1,
"sandNum":1,
"reedNum":1,
"stoneNum":1,
"grainOnStorageNum":1,
"vegeOnStorageNum":1,
"grainOnFieldNum":1,
"vegeOnFieldNum":1,
"grainDoingNum":1,
"vegeDoingNum":1,
"remainedFence":1,
"remainedBarn":1,
"remainedFamily":1,
"adultNum":1,
"babyNum":1,
"woodHouseNum":1,
"sandHouseNum":1,
"stoneHouseNum":1,
"fieldNum":1,
"foodNum":1,
"remainedJobCard": ["asdf"],
"usedJobCard": [],
"remainedMainFacilityCard": ["tlqkf wlsWk whssk aksgsp"],
"usedMainFacilityCard": [],
"remainedSubFacilityCard":["vvvv"],
"usedSubFacilityCard":[],
"numOfBeggingToken":0
}
```
오타..없음.........확인함....

feature: 게임 데이터 패치 기능

---

config/baseResponseStatus.js
controllers/socketController.js
models/GameStatus.js
services/gameService.js

* 순서는 당장 바뀌는 게 아니라 라운드가 바뀔 때 바뀌는 거라 데이터를 바로 바꿔줄 수가 없어서 gameStatus에 nextOrder 컬럼 새로 만들었음.
* 그래서 라운드 시작할 때는 nextOrder 값 order값이랑 똑같이 해두고 라운드 끝날 때 업데이트해줘야 할 듯...
* data에서 goods이 두 개 이상 들어올 때 순서는 반드시 order -> 보조설비 순으로 들어와야 함.
* prettier 때문에 수정사항 많아보이지만 아래에 써둔 부분에만 기능적 수정사항 있음...
* controllers/socketController.js Meeting Place
* services/gameService.js updateOrder
* models/GameStatus.js
* config/baseResponseStatus.js

feat: useActionSpace 회합 장소

---

package-lock.json
package.json

1. npm run dev
- 기존의 nodemon 이용한 방법
2. npm run start
- pm2 이용한 방법

feat: pm2 설정

---

controllers/socketController.js
models/index.js
services/gameService.js
services/roomService.js

현재 응답은 
https://www.notion.so/ec37de9dc1584754abfdd40b728609f0?pvs=4
이런 식인데 걍 확인용으로 볼 수 있게만 해놓은 거고 이따 얘기해봅시다 ...
그리고 일단 턴 종료에 대한 의문점이 해결되지 않아서 걍 다른 정보 전송 없이 정말 단순히 종료를 알려주는 것만 구현했음.

feat: 라운드 시작하기/종료하기 기능 구현

---

controllers/socketController.js
models/Card.js
models/GameStatus.js
models/index.js
services/gameService.js

울타리 친 외양간 구현 안 함
그리고 cageArea 새로 만듦

feat: 게임 종료하기(점수 계산) 기능 구현

---

controllers/socketController.js
models/Card.js
modules/utility.js
services/gameService.js

* 보조 설비 비용 지불 기능 
* 보조 설비 여물통 -> 점수 계산 시 효과
* 보조 설비 경질 자기 -> 아무 때나 사용할 수 있도록 구현
* 보조 설비 병 -> 점수 계산 시 효과
* 카드 테이블 cardKind 컬럼 추가
잠이 안 와서 ...

feat: 보조 설비 비용 지불, 기능 구현

---

controllers/socketController-roomSocket.js

모든 소켓 모두에게 보내도록 구현함.
방 하나에서 이루어지는 게임 하나를 가정했으므로 모든 소켓 모두에게 보내주도록 수정했음.

feat: 모든 소켓 모두에게 보내도록 구현

---

controllers/socketController.js
services/gameService.js

라운드 시작 수정
* 아기 성장하도록 구현
* 소규모 농부 효과 상관없이 두 플레이어들의 status 다 보내도록 수정
* 설비 사용 시 vegeOnStorage 말고 vege로 받도록 수정

feat: 라운드 시작 수정

---

models/GameStatus.js

이상한 컬럼이 있어요ㅠ
그래서 지웟어요 ㅠ
그런 건 없어요 ㅠ

chore: 이건 왜 안 지워졌냐

---

controllers/socketController.js

* 이상한 공백이 있어서 수정했어요
* Hard ceramics -> Hard ceramics

chore: 이상한 공백 수정

---

models/GameStatus.js

fix: 외양간 추가

---

services/gameService.js

등호를 수정했어요.
등호가 두 개 들어가야 하는데 한 개 들어가 있더군요...
급해서 걍 머지합니당~

fix: 등호 수정

---

models/Card.js

주요 설비 카드 이름 변경
* Stove -> Stove1
* Brazier -> Brazier1

chore: 주요 설비 카드 이름 변경

---

controllers/socketController.js
services/gameService.js

updateGoods, getPlayerStatus 시 남은 주요 설비도 emit하도록 구현

feat: updateGoods, getPlayerStatus 시 남은 주요 설비도 emit하도록 구현

---

models/Card.js
services/gameService.js

* Card 테이블에 이런저런 수정을 했어요...
* field 컬럼에 맞춰 점수 계산 방식 수정했어요...
* Card 테이블에 직업 카드가 없길래 추가했어요...
* startGame에서 Hard ceramic -> Hard ceramics로 수정했어요...
* Card 테이블 데이터 Hard ceramics 뒤에 공백이 하나 있어서 조회가 안 되길래 지웠어요...
* 카드 점수 입력 안 된 게 있길래 수정했어요...
* field 컬럼이 바뀌어서 점수 계산 방식 수정했어요...
**_이제 점수 계산이 잘 될 거예요!!_**

feat, chore: Card 테이블 수정 및 점수 계산 시 field 계산 방식 수정

---

controllers/socketController.js
services/gameService.js

* 라운드 스킵할 때 누적칸 관련 정보도 emit하도록 했삼
* accResult로 누적칸 관련 정보도 보내도록 했삼
* 일단 YOLO~!할래용 문제있음 담에 수정~

feat: 라운드 스킵 후 누적칸 관련 정보도 emit하도록 구현

---

controllers/socketController.js

각 브라우저에서 데이터를 주고 받기 위한 socket event 추가
예를 들어.. 브라우저에서 `양시장`을 사용한 경우, 받아온 양을 농장의 빈 울타리 안에 짓는다고 했을 때, 다른 플레이어의 브라우저에서도 해당 내용이 보여야 한다. 때문에 그냥 해당 socket event를 통해 처리하기로 함.

feat: 브라우저끼리 데이터 전송을 위한 socket event

---

services/gameService.js

foreach문 -> for of문 async
foreach문 -> for of문 async

fix: foreach -> for of async

---

controllers/actionSocketController.js
modules/utility.js

fix: 빵굽기 updateGoods 변경된 파라미터 적용
fix: 빵굽기 updateGoods 변경된 파라미터 적용

fix: 빵굽기 updateGoods 변경된 파라미터 적용

---

services/gameService.js

endTurn 응답 수정
요청한 userId에 해당하는 gameStatus만 보내주도록 수정

chore: endTurn 응답 수정
